name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Cambia a 'master' si tu rama principal se llama así

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Configurar Gradle
        uses: gradle/actions/setup-gradle@v3
        
      - name: Dar permisos de ejecución a gradlew
        run: chmod +x gradlew

      - name: Compilar Distribución WebAssembly
        run: ./gradlew :composeApp:wasmJsBrowserDistribution

      - name: Compilar Distribución WebAssembly
        # Tarea de Gradle estándar de KMP para compilar la web de producción
        run: ./gradlew :composeApp:wasmJsBrowserDistribution 

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v4

      - name: Subir Artefactos Compilados
        uses: actions/upload-pages-artifact@v3
        with:
          # Ruta por defecto donde Compose genera los archivos finales HTML/Wasm
          path: './composeApp/build/dist/wasmJs/productionExecutable'

      - name: Desplegar en GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
